version: "3.1"
services:
  web:
    build: .
    restart: always
    volumes:
      - api-sync:/usr/src/app
    devices:
        - "/dev/vchiq:/dev/vchiq"
    privileged: true
    ports:
     - "80:80"             #http

volumes:
  api-sync:
    external: true